# Usa una imagen de Node.js
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del proyecto
COPY package*.json ./
RUN npm install

# Copia el código fuente restante
COPY . .

# Expone el puerto 3001
EXPOSE 3003

# Comando para ejecutar la aplicación
CMD ["npm", "run", "dev"]
